### ISSUE TITLE
error

### ISSUE THREAD

**Issue by finnie2006** [Gertje823/magister2google#2]
nadat ik de windows open om in te loggen op google

```
Traceback (most recent call last):
  File "magister2google.py", line 108, in <module>
    main()
  File "magister2google.py", line 45, in main
    r = s.get(f"https://{base_url}/api/account", headers=headers).json()
  File "/home/finn/.local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/finn/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/finn/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/finn/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1297, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.8/http/client.py", line 1229, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)
```

**Comment by bertocus** [comment]
Gebruik je toevallig Firefox?
Ik had hetzelfde probleem. Komt omdat het bearer token van Magister ingekort wordt door de devtools waardoor je niet het hele token krijgt als je hem handmatig selecteert en kopieert. 
Op te lossen (in Firefox) door simpelweg rechts te klikken en "kopiëren" te kiezen zonder eerst het token te selecteren.

**Comment by Gertje823** [comment]
@finnie2006 Ik heb het script bijgewerkt. Je hoeft nu niet langer de Bearer token vanuit de browser te kopiëren. Je kunt je gebruikersnaam en wachtwoord in het script zetten waarmee het script inlogt. Als het goed is zal dat dit issue ook oplossen.
Ik zal het issue voor nu sluiten. Mocht je deze error toch nog tegenkomen kan je hem heropenen.

**Comment by finnie2006** [comment]
sorry haha, maar ik wil het draaien op mijn ubuntu server, maar dat lukt nu niet
