### ISSUE TITLE
Cannot open chromium

### ISSUE THREAD

**Issue by finnie2006** [Gertje823/magister2google#3]
I want to run it in Ubuntu server, but that is not possible right now, and i also tried it in windows for testing but also not working
Ubuntu server
````
finn@Finn-Pc:~/magister2google$ python3 magister2google.py
Logging in to Magister...
[INFO] Starting Chromium download.
100%|████████████████████████████████████████████████████████████████████████████████| 109M/109M [00:10<00:00, 10.6Mb/s]
[INFO] Beginning extraction
[INFO] Chromium extracted to: /home/finn/.local/share/pyppeteer/local-chromium/588429

Traceback (most recent call last):
  File "magister2google.py", line 64, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "magister2google.py", line 43, in main
    browser = await launch({"headless": True, "args": ["--start-maximized"]})
  File "/home/finn/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/finn/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/finn/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

finn@Finn-Pc:~/magister2google$
````
Windows
````
PS C:\Users\Finnt\Downloads\magister2google-main> python magister2google.py
Logging in to Magister...
C:\Users\Finnt\Downloads\magister2google-main\magister2google.py:64: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(main())
Traceback (most recent call last):
  File "C:\Users\Finnt\Downloads\magister2google-main\magister2google.py", line 64, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Finnt\Downloads\magister2google-main\magister2google.py", line 43, in main
    browser = await launch({"headless": True, "args": ["--start-maximized"]})
  File "C:\Users\Finnt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\Finnt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyppeteer\launcher.py", line 148, in launch
    self.proc = subprocess.Popen(  # type: ignore
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail
PS C:\Users\Finnt\Downloads\magister2google-main>
````

**Comment by Gertje823** [comment]
Did you install all the dependencies for pyppeteer on linux?
`sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`
After installing them the script should work.

For Windows:
It works for me on Windows I am running Python 3.8.9

**Comment by finnie2006** [comment]
hmm 
```
finn@Finn-Pc:~/magister2google$ python3 magister2google.py
Logging in to Magister...
Hi Finn
Found 117 events
Syncing wi - dth - t3c
Syncing wi - dth - t3c
Syncing lo - tba - t3c
Syncing lo - tba - t3c
Traceback (most recent call last):
  File "magister2google.py", line 160, in <module>
    main()
  File "magister2google.py", line 114, in main
    soup = BeautifulSoup(item['Inhoud'], 'lxml')
  File "/home/finn/.local/lib/python3.8/site-packages/bs4/__init__.py", line 248, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
finn@Finn-Pc:~/magister2google$
```
edit:
pip3 install lxml
 this kinda fixed it, but after it synced some i get this

```
Traceback (most recent call last):
  File "magister2google.py", line 139, in main
    create_event(event, creds, item['Start'], item['Omschrijving'],service)
  File "magister2google.py", line 148, in create_event
    event = service.events().insert(calendarId=Calendarid, body=event).execute()
  File "/home/finn/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/finn/.local/lib/python3.8/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Rate Limit Exceeded". Details: "[{'domain': 'usageLimits', 'reason': 'rateLimitExceeded', 'message': 'Rate Limit Exceeded'}]">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "magister2google.py", line 160, in <module>
    main()
  File "magister2google.py", line 142, in main
    patch_event(event, creds, item['Start'], item['Omschrijving'], hash,service)
  File "magister2google.py", line 155, in patch_event
    event = service.events().patch(calendarId=Calendarid, body=event, eventId=id).execute()
  File "/home/finn/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/finn/.local/lib/python3.8/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events/323032322d30362d30375430393a30353a30302e303030303030305a323032322d30362d30375430393a34353a30302e303030303030305a?alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
finn@Finn-Pc:~/magister2google$
```
it says it reached the ratelimit, can you make a bit slower maybe

**Comment by Gertje823** [comment]
I thought I fixed that. Maybe it is not slow enough. I'll take a look at it tonight

**Comment by finnie2006** [comment]
misschien kun je ook een config file toe voegen waar je het aantal weken kunt instellen dat hij moet syncen, en na hoelang hij opnieuw moet syncen zodat rooster wijzigingen ook door komen

**Comment by Gertje823** [comment]
In principe kan je hem als cronjob runnen. Als er wijzigingen zijn voor het event die al bestaat met dezelfde begin en eind tijd, dan zou hij het bestaande event updaten met de nieuwe informatie. Helaas heb ik geen actief Magister account om dit mee te testen.

**Comment by finnie2006** [comment]
het werkt top, maar kun je misschien toevoegen dat je kunt in stellen dat hij na X minuten opnieuw doet, ik wil het dan in docker draaien
